

pg_dump <options> <db_name>

exporting the database dvdrental to dvdrental-backup.sql:
pg_dump -U postgres dvdrental > dvdrental-backup.sql

Exporting a database (as a TAR archive)
Next, we will export the database as an archive. The following command will export it in a TAR format:
pg_dump -U postgres -F c dvdrental > dvdrental.tar

Exporting a database (as a compressed archive)
pg_dump -U postgres dvdrental | gzip > dvdrental.gz
pg_dump -U postgres --compress=9 dvdrental > dvdrental.tar

Exporting a database (directory format)
exporting the database dvdrental to the directory dvdrental-backup:
pg_dump -U postgres -F d dvdrental -f dvdrental-backup/


Backing up a single table
pg_dump -U postgres -t students example_backups > ~/Example_Dumps/students.sql

Backing up multiple tables
pg_dump -U postgres -W -t classes -t students -d example_backups > ~/Example_Dumps/all_tables.sql
pg_dump -h 10.45.195.2 -U postgres -W -t nation -t orders -t part -t partsupp -t region -t supplier -t lineitem -t customer -d mytpch > example_tables.sql


Exporting all databases
If you need to make a complete backup of the PostgreSQL database server, then you can use pg_dumpall.

pg_dumpall -f full_backup.sql

export the roles only:
pg_dumpall --roles-only -U postgres > all_db_roles.sql

export schemas only:
pg_dumpall --schema-only -U postgres > all_db_schema.sql

export only the tablespace definitions:
pg_dumpall --tablespaces-only -U postgres > all_db_tablespaces.sql





restore the dvdrentaldatabase in tarfile format generated by the  pg_dump tool in the PostgreSQL backup database tutorial using the following command:

pg_restore --dbname=newdvdrental --verbose c:\pgbackup\dvdrental.tar
If you restore the database, which is the same as the one that you made the backup, you can use the following command:

pg_restore --dbname=dvdrental --create --verbose c:\pgbackup\dvdrental.tar


psql -U username --set ON_ERROR_STOP=on -f backupfile


